DROP TABLE IF EXISTS "account";
DROP TABLE IF EXISTS "session";
DROP TABLE IF EXISTS "verificationToken";
ALTER TABLE "user" DROP COLUMN IF EXISTS "email";
ALTER TABLE "user" DROP COLUMN IF EXISTS "emailVerified";