import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Link from "next/link";
import { AxiomWebVitals } from "next-axiom";

import "./globals.css";

import Image from "next/image";

import { cn } from "@/lib/cn";
import { AccountButton } from "@/components/ui/accountButton";
import { Button } from "@/components/ui/button";
import logoImage from "@/app/icon.svg";
import { Providers } from "@/app/providers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "POPGDP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <AxiomWebVitals />
        <body
          className={cn(
            "flex min-h-screen flex-col items-center bg-background px-16 font-sans antialiased",
            fontSans.variable,
          )}
        >
          <header className="flex w-full items-center justify-between py-12">
            <Button variant="link" className="pl-0 text-base font-bold" asChild>
              <Link href="/">
                <Image src={logoImage} alt="Popgdp logo" />
                <h1 className="px-4">POPGDP</h1>
              </Link>
            </Button>
            <AccountButton />
          </header>

          <main className="w-full max-w-[1120px] flex-grow">{children}</main>

          <footer className="w-full max-w-[1120px] border-t p-6 text-center text-xs font-semibold">
            © 2024 POPGDP. All rights reserved
          </footer>
        </body>
      </Providers>
    </html>
  );
}
