import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { AccountButton } from "@/components/ui/accountButton";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "POPGDP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="flex flex-col min-h-screen items-center gap-12 px-16 py-12">
          <div className="w-full justify-between items-center flex">
            <Button
              variant="link"
              className="text-3xl font-mono font-bold"
              asChild
            >
              <Link href="/">POPGDP</Link>
            </Button>
            <AccountButton />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
