export const MOCK_SUBMISSION_DATA = {
  image: {
    id: "imageId",
    placeholder: "",
    width: 100,
    height: 100,
  },
  name: "Submission Name",
  entityName: "Entity Name",
  email: "submission@email.com",
  duration: 200,
  budget: 200000,
  summary: "Summary",
  categoryId: "e2f0c3b1-c159-45f2-99c6-f3152ab3ac18",
  teamSummary: "Team Summary",
  idea: "Idea",
  reason: "Reason",
  state: "State",
  goals: "Goals",
  requirements: "Requirements",
  tbdb: "TBDB",
  tbd: "TBD",
};
