name: 🧪 Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT: true
      DRIZZLE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      AUTH0_SECRET: 810bd1ccbf7b1d388d98339ac86d420649bdb789c9ac0c1fad383820341b1773
      AUTH0_BASE_URL: "http://localhost:3000"
      AUTH0_ISSUER_BASE_URL: "https://YOUR_AUTH0_DOMAIN.auth0.com"
      AUTH0_CLIENT_ID: "YOUR_AUTH0_CLIENT_ID"
      AUTH0_CLIENT_SECRET: "YOUR_AUTH0_CLIENT_SECRET"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Check
        run: pnpm check
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium
      - name: Run migrations
        run: pnpm drizzle-kit push:pg
      - name: Run Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
